[ETFE-3980] - Notification of split movement event
hmrc/emcs-tfe-frontend pull request #156
Opened 2024-06-06 12:30 UTC by LewisMitchell

Fixes issue where print link would show on messages and movement history events despite JS being disabled. Also cleanup some JS code.

2024-06-07 09:32 UTC, james-work-account commented on app/assets/javascripts/app.js
Why these changes?

2024-06-10 13:29 UTC, MJCallahanPage requested changes
One small query, otherwise LGTM

2024-06-10 13:29 UTC, MJCallahanPage commented on app/viewmodels/helpers/messages/ViewMessageHelper.scala
> +      link = "#print-dialogue", messageKey = "viewMessage.link.printMessage.description", id = Some("print-link"), classes = "govuk-link print-page govuk-!-display-none"
Is this right? Don't you just need to add `js-enabled` ?

2024-06-11 15:07 UTC, MJCallahanPage approved these changes
Approved 🟢

2024-06-11 15:25 UTC, merged