[ETFE-4005] Drill-down on EVN-11: Report of receipt submitted
hmrc/emcs-tfe-frontend pull request #165
Opened 2024-06-13 13:00 UTC by james-work-account

2024-06-17 09:04 UTC, MJCallahanPage requested changes

2024-06-17 09:04 UTC, MJCallahanPage commented on app/viewmodels/helpers/events/MovementEventHelper.scala
> +  def rorConsigneeCard(event: MovementHistoryEvent)(implicit movement: GetMovementResponse, messages: Messages): Html = {
Couldn't the existing `Consignee` card be updated for this? I'd have thought this content would have been consistent everwhere?

2024-06-17 09:04 UTC, MJCallahanPage commented on app/viewmodels/helpers/events/MovementEventHelper.scala
> +  def rorDestinationCard(event: MovementHistoryEvent)(implicit movement: GetMovementResponse, messages: Messages): Html = {
Couldn't the existing `Place of Destination` card be updated for this? I'd have thought this content would have been consistent everywhere?

2024-06-17 09:04 UTC, MJCallahanPage commented on app/viewmodels/helpers/events/MovementEventHelper.scala
> +  def rorExportCard(event: MovementHistoryEvent)(implicit movement: GetMovementResponse, messages: Messages): Html = {
Couldn't the existing `Export` information card be updated for this? I'd have thought this content would have been consistent everywhere?

2024-06-17 09:04 UTC, MJCallahanPage commented on app/viewmodels/helpers/events/MovementEventHelper.scala
> +  def rorItemsCard(event: MovementHistoryEvent, ie818ItemModelWithCnCodeInformation: Seq[IE818ItemModelWithCnCodeInformation])
Couldn't the existing `Items` information card be updated for this? I'd have thought this content would have been consistent everywhere?

2024-06-18 09:01 UTC, james-work-account commented on app/viewmodels/helpers/events/MovementEventHelper.scala
> +    } yield {
it's basically a guard. If this returns false, anything after it in the `for` section will be skipped, as will the `yield` stuff, so it'll bail out and return None early. See https://docs.scala-lang.org/scala3/book/control-structures.html#using-a-for-expression-as-the-body-of-a-method

2024-06-18 09:19 UTC, james-work-account commented on app/viewmodels/helpers/events/MovementEventHelper.scala
> +          Some(summaryListRowBuilder(s"movementHistoryEvent.${event.eventType}.rorExport.customsOfficeCode", reportOfReceipt.destinationOffice))
Double checked, my assumption was correct - will remove this TODO

2024-06-18 10:26 UTC, MJCallahanPage approved these changes
LGTM 🟢

2024-06-18 12:08 UTC, merged