ETFE 2355 - Add navigation banner to every page in the service
hmrc/emcs-tfe-frontend pull request #52
Opened 2023-12-19 14:02 UTC by machinesleet

2023-12-20 08:47 UTC, LewisMitchell requested changes
The spacing between `Home` and `< Back` is quite small and could be difficult to interact for users with dexterity issues, it may be worth increasing the margin between these elements?
![image](https://github.com/hmrc/emcs-tfe-frontend/assets/53828896/974684cc-fe3f-4cdd-af23-a565a944d587)

Also the navbar section doesn't change when the user clicks 'Movements', for example:
https://github.com/hmrc/emcs-tfe-frontend/assets/53828896/bfff582b-7a1a-4470-9a20-f375be61a036

2023-12-20 10:00 UTC, machinesleet commented on app/controllers/predicates/AuthActionHelper.scala
> +  def authorisedWithData(ern: String): ActionBuilder[DataRequest, AnyContent] =
When I removed the getMessageStatistics call in the AccountHomeController, the call to authorisedDataRequestAsync required the block to return a Future[Result]. I ended up having to wrap the view in a Future.successful to satisfy that type, whereas authorisedWithData didn't require this. Happy to change if you have any suggesstions.

2023-12-20 10:44 UTC, machinesleet commented
@LewisMitchell  It looks like the spacing of the Back button matches the prototype. Is it worth asking design? 
I'll look in to the navbar section issue

2023-12-20 17:05 UTC, LewisMitchell commented on app/views/components/navigation_bar.scala.html
> +                        <a id="navigation-home-link" class="moj-primary-navigation__link" @if(pageTitle == messages("viewMovement.title")) { aria-current="page" } href="@appConfig.emcsTfeHomeUrl">@me
Matching on page title can be risky, each page will have a different title. IMO I think having some kind of viewmodel object that we pass to this component would be better. Like so:
https://github.com/hmrc/emcs-tfe-frontend/commit/f43725b4a1c2276c1c4c7d88604c69ffbce9a7ca

2023-12-22 09:52 UTC, MJCallahanPage requested changes
One small tweak to remove the custom CSS

2023-12-22 09:52 UTC, MJCallahanPage commented on app/assets/stylesheets/application.scss
> +    margin-top: 30px;
Probably better to use the existing `!important` CSS classes that you can use for alignment within the GovUk stylesheets.

https://design-system.service.gov.uk/styles/spacing/#overriding-spacing

This is a better option as the spacing resizes dynamically based on the screen size which is important for smaller devices such as mobiles.

2023-12-22 09:52 UTC, MJCallahanPage commented on app/views/templates/Layout.scala.html
> +        @govukBackLink(BackLinkViewModel(href = "#").withCssClass("js-visible").withCssClass("emcs-tfe-frontend-back-link"))
Switch this to something like: `govuk-!-margin-top-6`

2023-12-27 16:52 UTC, james-work-account submitted a review, later dismissed

2023-12-27 16:52 UTC, hmrc-web-operations commented
Thank you for submitting a pull request on this HMRC repository. A member of the HMRC team will review your changes and action accordingly.

HMRC reviewer: please reference [this runbook](https://github.com/hmrc/build-and-deploy/blob/main/runbooks/reviewing_external_pull_requests.md) for guidance on how to proceed.

2023-12-27 16:53 UTC, james-work-account approved these changes

2023-12-27 16:55 UTC, james-work-account commented
retest

2023-12-27 16:57 UTC, merged